-- Image alignment framing for frontend-displayed images
ALTER TABLE "Project" ADD COLUMN "imageFocusX" INTEGER NOT NULL DEFAULT 50;
ALTER TABLE "Project" ADD COLUMN "imageFocusY" INTEGER NOT NULL DEFAULT 50;
ALTER TABLE "Project" ADD COLUMN "imageZoom" INTEGER NOT NULL DEFAULT 100;

ALTER TABLE "NewsPost" ADD COLUMN "imageFocusX" INTEGER NOT NULL DEFAULT 50;
ALTER TABLE "NewsPost" ADD COLUMN "imageFocusY" INTEGER NOT NULL DEFAULT 50;
ALTER TABLE "NewsPost" ADD COLUMN "imageZoom" INTEGER NOT NULL DEFAULT 100;

ALTER TABLE "HeroSlide" ADD COLUMN "imageFocusX" INTEGER NOT NULL DEFAULT 50;
ALTER TABLE "HeroSlide" ADD COLUMN "imageFocusY" INTEGER NOT NULL DEFAULT 50;
ALTER TABLE "HeroSlide" ADD COLUMN "imageZoom" INTEGER NOT NULL DEFAULT 100;

ALTER TABLE "Page" ADD COLUMN "heroImageFocusX" INTEGER NOT NULL DEFAULT 50;
ALTER TABLE "Page" ADD COLUMN "heroImageFocusY" INTEGER NOT NULL DEFAULT 50;
ALTER TABLE "Page" ADD COLUMN "heroImageZoom" INTEGER NOT NULL DEFAULT 100;

ALTER TABLE "Tender" ADD COLUMN "heroImageFocusX" INTEGER NOT NULL DEFAULT 50;
ALTER TABLE "Tender" ADD COLUMN "heroImageFocusY" INTEGER NOT NULL DEFAULT 50;
ALTER TABLE "Tender" ADD COLUMN "heroImageZoom" INTEGER NOT NULL DEFAULT 100;

ALTER TABLE "PageSection" ADD COLUMN "imageFocusX" INTEGER NOT NULL DEFAULT 50;
ALTER TABLE "PageSection" ADD COLUMN "imageFocusY" INTEGER NOT NULL DEFAULT 50;
ALTER TABLE "PageSection" ADD COLUMN "imageZoom" INTEGER NOT NULL DEFAULT 100;
