-- AlterEnum
ALTER TYPE "AuditAction" ADD VALUE 'ENQUIRY_DELETED';

-- AlterTable
ALTER TABLE "Enquiry" ADD COLUMN IF NOT EXISTS "isDeleted" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Enquiry" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "Enquiry" ADD COLUMN IF NOT EXISTS "deletedBy" TEXT;
