-- AlterTable
ALTER TABLE "BoardMember" ADD COLUMN "photoFocusX" INTEGER NOT NULL DEFAULT 50;
ALTER TABLE "BoardMember" ADD COLUMN "photoFocusY" INTEGER NOT NULL DEFAULT 50;

-- AlterTable
ALTER TABLE "LeadershipMember" ADD COLUMN "photoFocusX" INTEGER NOT NULL DEFAULT 50;
ALTER TABLE "LeadershipMember" ADD COLUMN "photoFocusY" INTEGER NOT NULL DEFAULT 50;
